= SUSE Linux Enterprise Documentation

= High Availabilty Extension

This is the source for the official SUSE Linux Enterprise High Availabilty
Extension documentation.

This repository hosts the documentation sources including translations (if
available) for the following manuals:

* Administration Guide
* Geo Clustering Quick Start
* NFS Storage with DRBD and Pacemaker Quick Start

Released versions of the documentation have been published at
https://www.suse.com/documentation/sle-ha/.

== Branches

.Overview of important branches
[options="header"]
|====================================================
| Name                   | Purpose
| `trans/SLEHA12`        | Translations from Dublin
| `maintenance/SLEHA12`  | Maintenance branch (DB4)
|====================================================


== Contributing

If you would like to contribute, please fork this repository and send
pull requests. Always use the `develop` branch for your edits! +
Contributors with direct access to the repository are encouraged to use the
git-flow-avh workflow (package `git-flow-avh`). However, this is not a must
;-).

.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is
reserved for releases only. Always commit to `develop`.

== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). Ideally, you should
  get these from the repository `Documentation:Tools`. However, slightly
  older versions are also available from the SLE and openSUSE repositories.
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF
** `$ daps -d DC-<YOUR_BOOK> html`: Build a HTML
** Learn more at https://opensuse.github.io/daps
