= SUSE Linux Enterprise Documentation

image:https://travis-ci.org/SUSE/doc-sleha.svg?branch=develop["Build Status", link="https://travis-ci.org/SUSE/doc-sleha"]

= High Availabilty Extension

This is the source for the official SUSE Linux Enterprise High Availabilty
Extension documentation.

This repository hosts the documentation sources including translations (if
available) for the following manuals:

* Administration Guide
* Geo Clustering Quick Start
* Geo Clustering Guide
* NFS Storage with DRBD and Pacemaker Quick Start
* Installation and Setup Quick Start
* Pacemaker Remote Quick Start

Released versions of the documentation are published at
https://www.suse.com/documentation/sle-ha/.

Beta versions can be found at https://susedoc.github.io/#sleha, where all commits to maintenance and development branches are automatically build.

== Branches

.Overview of important branches
[options="header"]
|================================================
| Name            | Purpose
| `develop`        | doc development (latest development version)
| `maintenance/*`  | maintenance for released versions
| `trans/*`        | translations for released versions
| `master`         | latest released version 
|================================================

== Reporting Bugs

Bugs are collected on https://bugzilla.suse.com. If possible, please check for
duplicates before creating a new report. When creating a new report, use
`SUSE Linux Enterprise High Availability Extension` as product. In the next step, select 
the product version where you found the bug. As component select `Documentation`.


== Contributing

If you would like to contribute, please fork this repository and send
pull requests. Always use the `develop` branch for your edits! +
Contributors with direct access to the repository are encouraged to use the
git-flow-avh workflow (package `git-flow-avh`). However, this is not a must
;-). For help on style and structure, refer to the https://doc.opensuse.org/products/opensuse/Styleguide/opensuse_documentation_styleguide_sd/[Documentation Styleguide]. 


.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is
reserved for releases only. Always commit to `develop`.

== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). Ideally, you should
  get these from the repository `Documentation:Tools`. However, slightly
  older versions are also available from the SLE and openSUSE repositories.
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build a multi-page HTML document
** Learn more at https://opensuse.github.io/daps


== License

The content of this project itself is licensed under the https://www.gnu.org/licenses/fdl-1.2.html[GFDL 1.2].

