= SUSE Linux Enterprise Documentation

= High Availability Extension

This is the source for the official SUSE Linux Enterprise High Availabilty
Extension documentation.

This repository hosts the documentation sources (including translations, if
available) for the following manuals:

* Administration Guide
* Geo Clustering Quick Start
* Geo Clustering Guide
* NFS Storage with DRBD and Pacemaker Quick Start
* Installation and Setup Quick Start
* Pacemaker Remote Quick Start

Released versions of the documentation are published at
https://www.suse.com/documentation/sle-ha/.

Beta versions can be found at https://susedoc.github.io/#sleha, where all commits to the master branch and the maintenance branches are automatically build.

== Branches

***On Sep 2, 2019, we changed to a new branching model. This entailed having to force push the
master branch. ***

* *Use the master branch* as the basis of your commits/of new feature branches.

* The *develop branch has been deleted* on the server. Do not to push to the `develop` branch.
  Your changes may go lost in the medium term and never make it to the proper branch.

* If you *created* a local clone or GitHub fork of this repo *before Sep 2, 2019, do the following*:

. Make sure that your `master` and `develop` branches do not contain any important changes.
  If there are changes on either branch, export them using `git format-patch` or put them on a
  different branch.

. Update the repo: `git fetch`
  (To also delete references to branches that do not exist anymore on the server, you can use
  `git fetch -p`.)

. Go to the master branch: `git checkout master`

. Hard-reset the state of the master branch to the state on GitHub: `git reset --hard origin/master`

. Delete your local develop branch: `git branch -D develop`


.Overview of important branches
[options="header"]

|================================================
| Name            | Purpose
| `master`         | doc development (latest development version)
| `maintenance/*`  | maintenance for released versions
| `trans/*`        | translations for released versions
|================================================

== Reporting Bugs

Bugs are collected on https://bugzilla.suse.com. If possible, please check for
duplicates before creating a new report. When creating a new report, use
`SUSE Linux Enterprise High Availability Extension` as product. In the next step, select the product version where you found the bug. As component select `Documentation`.


== Contributing

Thank you for contributing to this repo. When creating a pull request, please follow the guidelines below:

. If you want to contribute to the most recent release, create your pull request against the `master` branch (not `develop`). The `master` branch is is protected.

. If you want to contribute to a previous release, please create your pull request against the respective `maintenance/*` branch. These branches are also protected.

. Make sure all validation (Travis CI) checks are passed.

. For your pull request to be reviewed, please tag the relevant subject matter expert(s) from the development team (if applicable) and members of the documentation team: Tanja Roth (@taroth21), Thomas Schraitle (@tomschr).

. Implement the required changes. If you have any questions, ping a documentation team member in #susedoc on RocketChat.

. For help on style and structure, refer to the https://doc.opensuse.org/products/opensuse/Styleguide/opensuse_documentation_styleguide_sd/[Documentation Styleguide].

== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html.
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`).
* Install the documentation environment with the following command:
+
[source]
----
sudo /sbin/OneClickInstallUI https://gitlab.nue.suse.com/susedoc/doc-ymp/raw/master/Documentation.ymp
----

* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build a multi-page HTML document
** Learn more at https://opensuse.github.io/daps


== License

The content of this project itself is licensed under the https://www.gnu.org/licenses/fdl-1.2.html[GFDL 1.2].

